project:
  type: website
  output-dir: docs

website:
  title: "EIP Data Website"
  navbar:
    right:
      - text: "Home"
        href: main.qmd
      - text: "Clinical"
        menu:
          - text: HIV
            href: hiv.html
          - text: Hepatitis-C
            href: hcv.html
      - text: "Deliverables"
        menu:
          - text: CTR 2025/2026
            href: ctr_deliverables25.html
          - text: EHE 2025/2026
            href: ehe_deliverables25.html

format:
  html:
    theme:
      light: spacelab
      dark: darkly
    toc: true



